discovered a unique problem with factory girl
mdevoe12/youth_sports pull request #32
Opened 2017-09-03 00:39 UTC by brandonrandall

in the test, don't create an attribute of something that is in the
factory already

2017-09-03 03:14 UTC, mdevoe12 commented on spec/features/coach_dashboard_spec.rb
> +    expect(page).to have_css(".institution")
@brandonrandall 

The test on Line 41 looks solid. Can you test for have_content for institution, email and phone. Thanks!

2017-09-04 15:43 UTC, thedanielvogelsang commented
Is this a merge-able branch @brandonrandall ?

2017-09-04 15:48 UTC, thedanielvogelsang requested changes
There are several changes I think that should be made before we consider merging this branch. See pending review changes for my comments.

2017-09-04 15:48 UTC, thedanielvogelsang commented on app/views/coach_dashboard/show.html.erb
> +  <h2>Institution: <%= current_user.profile.institution %></h1>
checkout your h2 tag... its closed with /h1. Also, no need to wrap h2's in <p> tags. What about a <div>?

2017-09-04 15:48 UTC, thedanielvogelsang commented on app/views/coach_dashboard/show.html.erb
> +<p class="email">
same

2017-09-04 15:48 UTC, thedanielvogelsang commented on app/views/coach_dashboard/show.html.erb
> +  <%# binding.pry %>
binding.pry still in the code

2017-09-04 15:48 UTC, thedanielvogelsang commented on spec/features/coach_dashboard_spec.rb
> +# describe "user searches for stations by zip" do
What's all this commented-out code @brandonrandall ?

2017-09-05 20:28 UTC, closed without merging